openapi: '3.0.1'
info:
  title: Projeto achados e perdidos
  description: Todas implementações do projeto documentadas.
  version: '0.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'
  
paths:
  /objetos:
    get:
      summary: Acessar os objetos cadastrados.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    foto:
                      type: string
                    descricao:
                      type: string
                    data_encontrado:
                      type: string
                      format: date
                    data_limite:
                      type: string
                      format: date
                    objeto_entregue:
                      type: boolean
    post:
      summary: Cadastra um objeto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                foto:
                  type: string
                descricao:
                  type: string
                data_encontrado:
                  type: string
                  format: date
                data_limite:
                  type: string
                  format: date
                objeto_entregue:
                  type: boolean
      responses:
        201:
          description: Objeto cadastrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    description: O URI do novo objeto cadastrado.
                    type: string
  /objetos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Acessa um Objeto.
      responses:
        200:
          description: Ok
          content: 
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  foto:
                    type: string
                  descricao:
                    type: string
                  data_encontrado:
                    type: string
                    format: date
                  data_limite:
                    type: string
                    format: date
                  objeto_entregue:
                    type: boolean
    delete:
      summary: Apaga um Objeto.
      responses:
        204:
          description: Objeto apagado com sucesso.
        404:
          description: Objeto não encontrado
    put:
      summary: Altera um Objeto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                foto:
                  type: string
                descricao:
                  type: string
                data_encontrado:
                  type: string
                  format: date
                data_limite:
                  type: string
                  format: date
                objeto_entregue:
                  type: boolean
      responses:
        200:
          description: Ok.
        404:
          description: Página não encontrada
  
  /avisos:  # Novo endpoint
    get:
      summary: Acessar os avisos cadastrados.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    comunicado:
                      type: string
                    importante:
                      type: boolean
    post:
      summary: Cadastrar um aviso.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comunicado:
                  type: string
                importante:
                  type: boolean
      responses:
        201:
          description: Aviso cadastrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    description: O URI do novo aviso cadastrado.
                    type: string

  /avisos/{id}:  # Operações para avisos com ID específico
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Acessar um aviso específico.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  comunicado:
                    type: string
                  importante:
                    type: boolean
    delete:
      summary: Apagar um aviso.
      responses:
        204:
          description: Aviso apagado com sucesso.
        404:
          description: Aviso não encontrado.
    put:
      summary: Alterar um aviso.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comunicado:
                  type: string
                importante:
                  type: boolean
      responses:
        200:
          description: Aviso atualizado com sucesso.
        404:
          description: Aviso não encontrado.

  /categorias:  # Novo endpoint
    get:
      summary: Acessar as categorias cadastradas.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
    post:
      summary: Cadastrar uma categoria.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Categoria cadastrada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    description: O URI da nova categoria cadastrada.
                    type: string

  /categorias/{id}:  # Operações para categorias com ID específico
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Acessar uma categoria específica.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
    delete:
      summary: Apagar uma categoria.
      responses:
        204:
          description: Categoria apagada com sucesso.
        404:
          description: Categoria não encontrada.
    put:
      summary: Alterar uma categoria.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        200:
          description: Categoria atualizada com sucesso.
        404:
          description: Categoria não encontrada.
